name: root
description: Flutter Plugin to check Android device Root status and Run shell commands in android(only), use this plugin only for short period of processes.
version: 2.0.1
homepage: https://github.com/gokul1630/root

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.gokul.root
        pluginClass: RootPlugin
